name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image for testing
        run: docker build . --file Dockerfile.dev --tag ericndungutse/cicd_react_app
      - name: Run the test container
        run: docker run --rm ericndungutse/cicd_react_app npm test -- --coverage
