name: deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image for testing
        run: docker build . --file Dockerfile.dev --tag ericndungutse/cicd_react_app
      - name: Run the test container
        run: docker run --rm ericndungutse/cicd_react_app npm test -- --coverage

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t ericndungutse/cicd_react_app .

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name cicd-react-app \
            --version-label 20 \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-1-081385086583,S3Key=my-react-app.zip
          aws elasticbeanstalk update-environment \
            --environment-name Cicd-react-app-env \
            --version-label 20
